#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd

yunohost service add "$app" --description="Media tracker" --log="/var/log/$app/$app.log"

#=================================================
# INSTALL THE APP
#=================================================
ynh_script_progression "Installing the app..."

pushd "$install_dir"
	export NODE_ENV=production
 	ynh_hide_warnings ynh_exec_as_app npm ci
 	ynh_hide_warnings ynh_exec_as_app npm run build
popd

pushd "$install_dir"/server
	export NODE_ENV=production
 	ynh_hide_warnings ynh_exec_as_app npm ci --omit=dev
popd

#Remove unneeded files
ynh_safe_rm "$install_dir"/docker
ynh_safe_rm "$install_dir"/vscode
ynh_safe_rm "$install_dir"/docker-reverse-proxy
ynh_safe_rm "$install_dir"/.github
ynh_safe_rm "$install_dir"/.npm
ynh_safe_rm "$install_dir"/client/node_modules

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start" --wait_until="Aucune mise à jour disponible"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
